units:
  - cup
  - cups
  - teaspoon
  - teaspoons
  - tbsp
  - tablespoon
  - tablespoons
  - tsp
  - t
  - oz
  - ounce
  - ounces
  - lb
  - lbs
  - gram
  - grams
  - g
  - kg
  - ml
  - l
  - pint
  - pints
  - quart
  - quarts
  - liter
  - liters